/******************************************************************************
 
******************************************************************************/

#ifndef __DTV_CONTROLLER_DEFINE_H_
#define __DTV_CONTROLLER_DEFINE_H_

enum
{
	PARENTAL_CONTROL_OFF = 0,
	PARENTAL_CONTROL_ON,
};

enum
{
	RATING_L = 0,
	RATING_10 = 10,
	RATING_12 = 12,
	RATING_14 = 14,
	RATING_16 = 16,
	RATING_18 = 18,
};


enum GeneralDtvStatus
{
	GNRAL_STATUS_UNKNOWN	= 0,
	GNRAL_STATUS_DETECT_TUNER_DOING,
	GNRAL_STATUS_DETECT_TUNER_DONE,
	GNRAL_STATUS_OPEN_DTVPLAYER_DOING,
	GNRAL_STATUS_OPEN_DTVPLAYER_FAILED,
	GNRAL_STATUS_OPEN_DTVPLAYER_DONE,
	GNRAL_STATUS_CLOSE_DTVPLAYER_DOING,
	GNRAL_STATUS_CLOSE_DTVPLAYER_DONE,
	GNRAL_STATUS_SCANNING_CHANNEL,
	GNRAL_STATUS_PLAYING_CHANNEL,
};


enum DtvStatus
{
	DTV_STATUS_UNKNOWN	= 0,
    DTV_STATUS_SET_SCAN_DOING,
	DTV_STATUS_SET_SCAN_FAILED,
	DTV_STATUS_SET_SCAN_DONE,
	DTV_STATUS_SCAN_DOING,
	DTV_STATUS_SCAN_DONE,
	DTV_STATUS_STOP_SCAN_DOING,
	DTV_STATUS_STOP_SCAN_DONE,
	DTV_STATUS_PLAY_CHAN_DOING,
	DTV_STATUS_PLAY_CHAN_DONE,
	DTV_STATUS_DELETE_CHANNEL_DOING,
	DTV_STATUS_DELETE_CHANNEL_DONE,
	DTV_STATUS_FREE_CHANS_IN_DTVPLAYER_DOING,
	DTV_STATUS_FREE_CHANS_IN_DTVPLAYER_DONE,
	DTV_STATUS_SORT_DOING,
	DTV_STATUS_SORT_DONE,
	DTV_STATUS_RESET_DTV_DATA_DOING,
	DTV_STATUS_RESET_DTV_DATA_DONE,
	DTV_STATUS_RESTORE_CHAN_INFO_DOING,
	DTV_STATUS_RESTORE_CHAN_INFO_DONE,
};

enum SortChannel
{
    SORT_BY_LCN = 0,
    SORT_BY_HD_SD,
};


#endif //__DTV_CONTROLLER_DEFINE_H_

/******************************************************************************
	End
******************************************************************************/
